package operation;

public enum OperationType {
	USER_COUNT,
	POST_COUNT_PER_USER,
	POST_SUM,
	POST_AVERAGE_COUNT,
	POST_AVERAGE_LENGTH_PER_USER,
	POST_AVERAGE_LENGTH,
	POST_LENGTH_SUM,
	COMMENT_COUNT_PER_USER,
	COMMENT_SUM,
	COMMENT_AVERAGE_COUNT,
	COMMENT_AVERAGE_LENGTH_PER_USER,
	COMMENT_AVERAGE_LENGTH,
	COMMENT_LENGTH_SUM,
	TITLE_COUNT_PER_USER,
	TITLE_SUM,
	TITLE_AVERAGE_COUNT,
	TITLE_AVERAGE_LENGTH_PER_USER,
	TITLE_AVERAGE_LENGTH,
	TITLE_LENGTH_SUM,
}
